# Generated by Django 2.1.4 on 2019-01-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoujinMarketsM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=255)),
                ('market_version', models.IntegerField()),
                ('market_place', models.CharField(max_length=255)),
                ('market_date', models.DateField()),
                ('market_start_time', models.TimeField()),
                ('market_memo', models.TextField()),
            ],
        ),
    ]
