# Generated by Django 2.1.4 on 2019-01-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sokubaikai', '0002_auto_20190124_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doujinmarketsm',
            name='market_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doujinmarketsm',
            name='market_start_time',
            field=models.CharField(max_length=255),
        ),
    ]
